name: Python CI
env:
  APP_SECRET_KEY: "testing-secret-key"

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        env:
          FLASK_ENV: testing
          FLASK_APP: app
          PYTHONPATH: ${{ github.workspace }}
        run: pytest 

